@extends('index')
@section('slibar')
    @include('block.body')
@endsection
@section('donvitructhuoc')
    @include('block.donvitructhuoc')
@endsection
@section('bodychitieu')
    @include('block.bodychitieu')
@endsection
@section('tintuc')
    @include('block.tintuc')
@endsection
